export const enum LOGGER_LEVEL {
    DEBUG = "1",
    INFO = "2",
    WARN = "3",
    ERROR = "4"
  }

  export const enum LOGGER_CLASS {
    EDITOR = "EDITOR",
    RECOGNIZER = "RECOGNIZER",
    GRABBER = "GRABBER",
    BEHAVIORS = "BEHAVIORS",
    CONFIGURATION = "CONFIGURATION",
    PUBLIC_EVENT = "PUBLIC_EVENT",
    MODEL = "MODEL",
    CANVAS_RENDERER = "CANVAS_RENDERER",
    SVGRENDERER = "SVGRENDERER",
    SMARTGUIDE = "SMARTGUIDE",
    STYLEMANAGER = "STYLEMANAGER",
    UNDOREDO_MANAGER = "UNDOREDO_MANAGER",
    STROKE = "STROKE",
    INTERNALEVENT = "INTERNALEVENT"
  }

  export type TLoggerConfiguration = {
    [key in keyof typeof LOGGER_CLASS]: LOGGER_LEVEL
  }