/**
 * @group Client
 * @remarks List all errors generated by the backend with their descriptions
 */
export enum ClientError {
  NO_ACTIVITY = "Session closed due to no activity. Without a connection on your part, it will be permanently lost after an hour.",
  WRONG_CREDENTIALS = "Application credentials are invalid. Please check or regenerate your application key and hmackey.",
  TOO_OLD = "Session is too old. Max Session Duration Reached.",
  NO_SESSION_FOUND = "No sessions found. Without activation for 1 hour, sessions are deleted from the server. To avoid losing your work, use the json export, then import it this will create a new session.",
  UNKNOWN = "An unknown error has occurred.",
  ABNORMAL_CLOSURE = "MyScript recognition server is not reachable.",
  CANT_ESTABLISH = "Unable to establish a connection to MyScript recognition server. Check the host and your connectivity.",
  GOING_AWAY = "MyScript recognition server is going away, either because of a server failure or because the browser is navigating away from the page that opened the connection.",
  PROTOCOL_ERROR = "MyScript recognition server terminated the connection due to a protocol error.",
  UNSUPPORTED_DATA = "MyScript recognition server terminated the connection because the endpoint received data of a type it cannot accept. (For example, a text-only endpoint received binary data.)",
  INVALID_FRAME_PAYLOAD = "MyScript recognition server terminated the connection because a message was received that contained inconsistent data (e.g., non-UTF-8 data within a text message).",
  POLICY_VIOLATION = "MyScript recognition server terminated the connection because it received a message that violates its policy.",
  MESSAGE_TOO_BIG = "MyScript recognition server terminated the connection because a data frame was received that is too large.",
  INTERNAL_ERROR = "MyScript recognition server terminated the connection because it encountered an unexpected condition that prevented it from fulfilling the request.",
  SERVICE_RESTART = "MyScript recognition server terminated the connection because it is restarting.",
  TRY_AGAIN = "MyScript recognition server terminated the connection due to a temporary condition, e.g. it is overloaded and is casting off some of its clients.",
  BAD_GATEWAY = "MyScript recognition server was acting as a gateway or proxy and received an invalid response from the upstream server.",
  TLS_HANDSHAKE = "MyScript recognition server connection was closed due to a failure to perform a TLS handshake",
}

/**
 * @group Client
 */
export function mapCloseCodeToMessage(code: number): string | null {
  switch (code) {
    case 1000:
      return ""
    case 1001:
      return ClientError.GOING_AWAY
    case 1002:
      return ClientError.PROTOCOL_ERROR
    case 1003:
      return ClientError.UNSUPPORTED_DATA
    case 1006:
      return ClientError.ABNORMAL_CLOSURE
    case 1007:
      return ClientError.INVALID_FRAME_PAYLOAD
    case 1008:
      return ClientError.POLICY_VIOLATION
    case 1009:
      return ClientError.MESSAGE_TOO_BIG
    case 1011:
      return ClientError.INTERNAL_ERROR
    case 1012:
      return ClientError.SERVICE_RESTART
    case 1013:
      return ClientError.TRY_AGAIN
    case 1014:
      return ClientError.BAD_GATEWAY
    case 1015:
      return ClientError.TLS_HANDSHAKE
    default:
      return null
  }
}
